[workspace]
resolver = "2"
members = [
    "spinel",
    "spinel-cli",
    "xtask",
]

[workspace.package]
version = "0.2.0"
authors = ["Jake Swensen"]
description = "Control networking devices using the Spinel protocol."
repository = "https://github.com/twine-rs/spinel"
edition = "2021"
license = "MPL-2.0"
